# Generated by Django 2.0.1 on 2018-01-03 10:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptID', models.CharField(max_length=200)),
                ('deptName', models.CharField(max_length=200)),
                ('deptStDatetime', models.DateTimeField(default=datetime.datetime(2018, 1, 3, 10, 44, 47, 597236, tzinfo=utc), verbose_name='开始时间')),
                ('deptEndDatetime', models.DateTimeField(verbose_name='结束时间')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.CharField(max_length=200)),
                ('groupName', models.CharField(max_length=200)),
                ('groupStDatetime', models.DateTimeField(default=datetime.datetime(2018, 1, 3, 10, 44, 47, 598240, tzinfo=utc), verbose_name='开始时间')),
                ('groupEndDatetime', models.DateTimeField(verbose_name='结束时间')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankID', models.CharField(max_length=200)),
                ('rankName', models.CharField(max_length=200)),
                ('rankStDatetime', models.DateTimeField(default=datetime.datetime(2018, 1, 3, 10, 44, 47, 597236, tzinfo=utc), verbose_name='开始时间')),
                ('rankEndDatetime', models.DateTimeField(verbose_name='结束时间')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeID', models.CharField(max_length=200)),
                ('typeName', models.CharField(max_length=200)),
                ('typeStDatetime', models.DateTimeField(default=datetime.datetime(2018, 1, 3, 10, 44, 47, 598240, tzinfo=utc), verbose_name='开始时间')),
                ('typeEndDatetime', models.DateTimeField(verbose_name='结束时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=200, verbose_name='工号')),
                ('userName', models.CharField(max_length=200, verbose_name='用户名')),
                ('userPassword', models.CharField(max_length=200, verbose_name='密码')),
                ('userStDatetime', models.DateTimeField(default=datetime.datetime(2018, 1, 3, 10, 44, 47, 596236, tzinfo=utc), verbose_name='开始时间')),
                ('userEndDatetime', models.DateTimeField(verbose_name='结束时间')),
            ],
        ),
        migrations.AddField(
            model_name='type',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='rank',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='dept',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
