# Generated by Django 2.0.1 on 2018-01-03 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180103_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userDeptDR',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='user.Dept'),
        ),
    ]
